services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        networks:
            - mern
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "5000:5000"

        environment:
            - MONGO_URI=mongodb://database:27017/task
        networks:
            - mern
        depends_on:
            - database
    database:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - mern
        volumes:
            - mongo-data:/data/db

networks:
    mern:
        driver: bridge

volumes:
    mongo-data:
        driver: local
